---

sudo: "required"
dist: "xenial"

language: "python"

python:
  - "2.7"
  - "3.7"

before_install:
  - "sudo apt-get update && sudo apt-get install -y flake8"
  - "flake8 --ignore=E501 verdiff"

install:
  - "chmod +x verdiff"

script:
  - "DEBUG=1 ./verdiff 1.4.4 1.4.8"
  - "DEBUG=1 ./verdiff --framework rails 5.1.2 5.2.3 --project customname"
  - "DEBUG=1 ./verdiff --framework django 2.1.9 2.2.2"
  - "DEBUG=1 ./verdiff --framework laravel 5.6.33 5.8.17"
  - '[ ! -d phoenix ]'
  - '[ ! -f Dockerfile* ]'
  - '[ -z "$(docker container ls -qa)" ]'
  - '[ -z "$(docker image ls -q)" ]'
  - "DEBUG=1 ./verdiff 1.4.4 1.4.8 --save --keep-image --keep-dockerfile"
  - '[ -d phoenix ]'
  - '[ -f Dockerfile* ]'
  - '[ -z "$(docker container ls -qa)" ]'
  - '[ -n "$(docker image ls -q)" ]'
