name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Lint and test"
        run: |
          ./run ci:test
